print ("Answer following questions to get a personalized password dictionary\nIf you don't know any answer just skip by pressing enter")
first_name = input ("Enter victim\'s first name:")
second_name = input ("Enter victim\'s second name:")
third_name = input ("Enter victim\'s third name or nick name:")
type = input ("How is the victim: hard working/lazy:")
birth_date = input ("Enter victim\'s date of birth:")
aim = input ("Enter victim\'s aim:")
hobby = input ("Enter victim\'s hobby:")
passion = input ("Enter victim\'s passion:")
crush_first = input ("Enter victim\'s crush\'s first name:")
crush_second = input ("Enter victim\'s crush\'s second name:")
crush_third = input ("Enter victim\'s crush\'s third name:")
lucky_num = input ("Enter victim\'s lucky number:")
unlucky_num = input ("Enter victim\'s unlucky number:")
ideal = input ("Enter victim\'s ideal\'s name:")

print (first_name + "@" + lucky_num + third_name)